---
- name: Install
  aur:
    name: android-studio
  become: true
  become_user: aur_builder

- name: Copy desktop file
  copy:
    src: desktop/android-studio.desktop
    dest: "/home/{{ username }}/.local/share/applications/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy dock item
  template:
    src: dock/android-studio.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy config to import manually
  copy:
    src: config/android-studio-config.zip
    dest: "/home/{{ username }}/.config/jetbrains-zip-config/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
