---
- name: Install
  aur:
    name: android-studio
  become: true
  become_user: aur_builder

- name: Copy desktop file
  copy:
    src: desktop/android-studio.desktop
    dest: /home/aleksa/.local/share/applications/
    mode: 0755
    owner: aleksa
    group: aleksa

- name: Copy dock item
  copy:
    src: dock/android-studio.dockitem
    dest: /home/aleksa/.config/plank/dock1/launchers/
    mode: 0755
    owner: aleksa
    group: aleksa

- name: Copy config to import manually
  copy:
    src: config/android-studio-config.zip
    dest: /home/aleksa/.config/jetbrains-zip-config/
    mode: 0755
    owner: aleksa
    group: aleksa
