---
- name: Install
  aur:
    name: gravit-designer-bin
  become: true
  become_user: aur_builder

- name: Copy desktop file
  copy:
    src: desktop/gravit-designer.desktop
    dest: "/home/{{ username }}/.local/share/applications/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy dock item
  copy:
    src: dock/gravit-designer.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
