---
- name: Install ncruses5 compat libraries
  aur:
    name: ncurses5-compat-libs
  become: true
  become_user: aur_builder

- name: Install VMware
  aur:
    name: vmware-workstation
  become: true
  become_user: aur_builder

- name: Install VMware Keymaps
  aur:
    name: vmware-keymaps
  become: true
  become_user: aur_builder

- name: Copy configuration script
  become: true
  become_user: "{{ username }}"
  copy:
    src: scripts/vmware-setup.sh
    dest: ~/.config/vmware/
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0755

- name: Copy desktop file
  copy:
    src: desktop/vmware.desktop
    dest: "/home/{{ username }}/.local/share/applications/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy dock item
  template:
    src: dock/vmware.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
