---
- name: Install
  snap:
    name: sublime-text
    classic: yes
    state: present

- name: Remove current user config
  file:
    path: "/home/{{ username }}/.config/sublime-text-3/Packages/User"
    state: absent

- name: Clone settings
  git:
   repo: https://github.com/aleksa-sukovic/sublime-configuration.git
   dest: "/home/{{ username }}/.config/sublime-text-3/Packages/User"
   force: yes
