---
- name: Install
  aur:
    name: sublime-text-dev
    use: makepkg
  become: true
  become_user: aur_builder

- name: Copy desktop file
  copy:
    src: desktop/sublime.desktop
    dest: /home/aleksa/.local/share/applications/
    mode: 0755
    owner: aleksa
    group: aleksa

- name: Copy dock item
  copy:
    src: dock/sublime.dockitem
    dest: /home/aleksa/.config/plank/dock1/launchers/
    mode: 0755
    owner: aleksa
    group: aleksa

- name: Remove current user config
  file:
    path: /home/aleksa/.config/sublime-text-3/Packages/User
    state: absent

- name: Clone settings
  git:
   repo: https://github.com/aleksa-sukovic/sublime-configuration.git
   dest: /home/aleksa/.config/sublime-text-3/Packages/User
   force: yes
