---
# - name: Install
#   aur:
#     name: google-chrome
#   become: true
#   become_user: aur_builder

- name: Copy desktop file
  copy:
    src: desktop/google-chrome.desktop
    dest: "/home/{{ username }}/.local/share/applications/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy dock item
  template:
    src: dock/google-chrome.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
