---
- name: Install VLC Player
  pacman:
    name: vlc
    state: latest
    update_cache: yes

- name: Create VLC Player config directory
  file:
    path: /home/aleksa/.config/vlc
    state: directory
    owner: aleksa
    mode: 0755

- name: Configure VLC Player
  copy:
    src: vlc-config
    dest: /home/aleksa/.config/vlc/vlcrc
