---
- name: Install
  snap:
    name: phpstorm
    classic: yes
    state: present

- name: Copy config to import manually
  copy:
    src: config/php-storm-config.zip
    dest: "/home/{{ username }}/.config/jetbrains-zip-config/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
