---
- name: Install
  snap:
    name: gitkraken
    state: present

- name: Copy icon
  copy:
    src: icons/git-kraken.png
    dest: "/home/{{ username }}/Documents/Dock/Icons/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
