---
- name: Install
  aur:
    name: dbeaver
  become: true
  become_user: aur_builder

- name: Copy desktop file
  copy:
    src: desktop/dbeaver.desktop
    dest: "/home/{{ username }}/.local/share/applications/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy dock item
  copy:
    src: dock/dbeaver.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
