---
- name: Install
  pacman:
    name: git
    state: present
    update_cache: yes

- name: Configure username
  command: git config --global user.name "Aleksa Sukovic"

- name: Configure email
  command: git config --global user.email "sukovic.aleksa@gmail.com"
