---
- name: Install
  aur:
    name: visual-studio-code-bin
    use: makepkg
  become: true
  become_user: aur_builder

- name: Copy desktop file
  copy:
    src: desktop/visual-studio-code.desktop
    dest: /home/aleksa/.local/share/applications/
    mode: 0755
    owner: aleksa
    group: aleksa

- name: Copy dock item
  copy:
    src: dock/visual-studio-code.dockitem
    dest: /home/aleksa/.config/plank/dock1/launchers/
    mode: 0755
    owner: aleksa
    group: aleksa
