---
- name: Default desktop files
  copy:
    src: desktop/
    dest: "/home/{{ username }}/.local/share/applications/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Default desktop icons
  copy:
    src: icons/
    dest: "/home/{{ username }}/Documents/Dock/Icons/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Create default autostart application folder
  file:
    path: "/home/{{ username }}/.config/autostart/"
    state: directory
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0755

- name: Create AppImage application directory
  file:
    path: "/home/{{ username }}/Applications"
    state: directory
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0755
