---
# - name: Install
#   pacman:
#     name: intellij-idea-community-edition
#     state: latest
#     update_cache: yes

- name: Copy desktop file
  copy:
    src: desktop/intellij-community.desktop
    dest: "/home/{{ username }}/.local/share/applications/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy dock item
  copy:
    src: dock/intellij-community.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy icon
  copy:
    src: icons/intellij-community.png
    dest: "/home/{{ username }}/Documents/Dock/Icons/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy config to import manually
  copy:
    src: config/intellij-community-config.zip
    dest: "/home/aleks{{ username }}a/.config/jetbrains-zip-config/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
