---
- name: Install
  snap:
    name: intellij-idea-community
    classic: yes
    state: present

- name: Copy config to import manually
  copy:
    src: config/intellij-community-config.zip
    dest: "/home/aleks{{ username }}a/.config/jetbrains-zip-config/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
